### ISSUE TITLE
mergerepo_c noarch + multilib in koji bare mode

### ISSUE THREAD

**Issue by tkopecek** [rpm-software-management/createrepo_c#213] opened 2020-03-18 11:43 UTC
As more koji modes are introduced, we've hit a following problem:

When using "bare" mode (--pkgorigins --all), noarch multilib is not activated (it is only triggerred for --koji). I think, that the best option is to add separate option --noarch-multilib, so we don't pollute semantics for other options.

This one should directly solve https://pagure.io/koji/issue/1664. I'm not sure, if it will solve also https://pagure.io/koji/issue/1865, but maybe yes.

Do you've any opinion about this? (The other option is to expan arch list on koji's side, but I think, that all expansion code now lives in mergerepo_c, so it should be better to do it here).

(I can write a patch, if this is ok solution for you).

**Comment by kontura** [comment] 2020-03-19 13:14
I agree that its better to do it in mergerepo_c, so this solution works for me.

Maybe just the name `--noarch-multilib` seems a bit confusing to me. Does it mean that it will add the noarch to the list of architectures and expand all the possible specified architectures?

**Comment by tkopecek** [comment] 2020-03-19 14:58
AFAIK, it is about replicating this line: https://github.com/rpm-software-management/createrepo_c/blob/master/src/mergerepo_c.c#L262
But maybe, part of the problem lies also in 
https://github.com/rpm-software-management/createrepo_c/blob/master/src/mergerepo_c.c#L254

So, probably both pieces should be affected by that option. Any idea for better name (as second is not about noarch)?

**Comment by kontura** [comment] 2020-03-19 22:01
I have further looked at the issues and from https://pagure.io/koji/issue/1865 it seems that koji always passes the `-a` param to mergerepo_c so the https://github.com/rpm-software-management/createrepo_c/blob/master/src/mergerepo_c.c#L262 should never apply?

Also once some arch is passed it always adds the noarch: https://github.com/rpm-software-management/createrepo_c/blob/master/src/mergerepo_c.c#L193.

The way I understand it one issue it about https://github.com/rpm-software-management/createrepo_c/blob/master/src/mergerepo_c.c#L254 like you said, and the second one is https://github.com/rpm-software-management/createrepo_c/blob/master/src/mergerepo_c.c#L147 which is also set based on `options->koji`.

If am right, its still two separate things, but if we always want both maybe something like `--arch-expand`? dunno.

**Comment by tkopecek** [comment] 2020-03-20 14:20
Yep, it looks it is the right option. @mikem23 ?

**Comment by mikem23** [comment] 2020-03-25 15:03
As near as I can tell, the inclusion of noarch in this discussion is irrelevant and seems to be distracting from the point. The issue is the lack of inclusion of multilib arches when Koji runs mergerepos_c without `--koji`. I think mergrepos_c is correct to always include noarch.

So this is just another bit of magic behavior that we got with `--koji` that we didn't realize we'd be missing for the new cases. I think adding an option to get that behavior is the right thing, and I concur that `--arch-expand` sounds like a good name for that option (the earlier suggestion is not a good name because the behavior is not really related to noarch).

**Comment by mikem23** [comment] 2020-03-25 15:04
Side note: I almost wonder if koji passing the `-a $arch` option is even the right thing for koji to be doing.

**Comment by tkopecek** [comment] 2020-03-31 12:06
@kontura Is it ok this way?

**Comment by kontura** [comment] 2020-03-31 14:31
@tkopecek yes, I think so :slightly_smiling_face:

**Comment by slords** [comment] 2020-04-23 14:07
Would another option be to always have koji pass --koji so we get the expansion.  The reason I went to bare was that I wanted all the packages.  Maybe make it so we can pass --koji and --all to mergerepo.

**Comment by mikem23** [comment] 2020-04-28 13:52
The `--koji` option doesn't mean "koji is running this". It means perform the merge in a very particular way that matches what Koji originally wanted. For our newer modes, Koji doesn't want all of that behavior, so Koji cannot always pass this option.

**Comment by tkopecek** [comment] 2020-04-28 13:54
@kontura Do you'll have some cycles to do this, or should I submit some code?

**Comment by kontura** [comment] 2020-04-29 08:52
Ok, I can do it, it should be fairly straightforward.

**Comment by kontura** [comment] 2020-05-05 07:18
@tkopecek I have created https://github.com/rpm-software-management/createrepo_c/pull/218

**Comment by kontura** [comment] 2020-05-20 11:48
@tkopecek If you need this released in rhel, please create a bugzilla for it, otherwise it should land in our next fedora release (in f31, f32 and rawhide).

**Comment by tkopecek** [comment] 2020-05-20 12:48
Fedora is ok for now, thanks!

**Closed** 2020-05-20 13:35 UTC
