### ISSUE TITLE
Auto-detect compression appears to be broken for some files

### ISSUE THREAD

**Issue by dralley** [rpm-software-management/createrepo_c#353] opened 2023-03-24 02:26 UTC
If a file is downloaded to a temporary file, it may not necessarily retain the original extension.  I would still expect the magic number to be recognized but I'm seeing some *really* weird behavior with this.

Below I've downloaded the primary.xml.gz from two repos:

- https://dl.fedoraproject.org/pub/fedora/linux/updates/37/Everything/x86_64/repodata/
- https://download.copr.fedorainfracloud.org/results/audron/dexed/fedora-38-aarch64/repodata/

I've also renamed the file to remove the file extension on the 2nd attempt.  Strangely you can see that for one file it still works, and for the other file it doesn't.

```
In [1]: import createrepo_c as cr

In [2]: cr.detect_compression("fbe45ef42039fec552386d5c18de2175d7c525994ae20aed7fedd4a990891da7-prim
   ...: ary.xml.gz")
Out[2]: 3

In [4]: cr.detect_compression("fbe45ef42039fec552386d5c18de2175d7c525994ae20aed7fedd4a990891da7")
Out[4]: 3

In [5]: cr.detect_compression("af12533499469117e3824bc938bfc3208539deb44bbf56ec2612fc383b28a1f4-prim
   ...: ary.xml.gz")
Out[5]: 3

In [6]: cr.detect_compression("af12533499469117e3824bc938bfc3208539deb44bbf56ec2612fc383b28a1f4")
Out[6]: 1
```

Using the `file` command directly shows the same:

```
[dalley@thinkpad Downloads]$ file -i fbe45ef42039fec552386d5c18de2175d7c525994ae20aed7fedd4a990891da7 
fbe45ef42039fec552386d5c18de2175d7c525994ae20aed7fedd4a990891da7: application/gzip; charset=binary
[dalley@thinkpad Downloads]$ file -i af12533499469117e3824bc938bfc3208539deb44bbf56ec2612fc383b28a1f4 
af12533499469117e3824bc938bfc3208539deb44bbf56ec2612fc383b28a1f4: application/octet-stream; charset=binary
```

But the `gzip` magic number `1f8b` exists in both files?  This is extremely strange.  Why does file have problems with one but not the other?

```
[dalley@thinkpad Downloads]$ xxd fbe45ef42039fec552386d5c18de2175d7c525994ae20aed7fedd4a990891da7 | head
00000000: 1f8b 0800 0000 0000 0003 ec7d 5b97 db36  ...........}[..6
00000010: 92f0 7bff 0a1e bf8c 7362 a901 9004 c9ec  ..{.....sb......
00000020: 4cbe e3d8 8ec7 bb76 e2a4 9d49 765f fa80  L......v...Iv_..
00000030: 0028 31a6 4485 a4ba ddf9 f55f 01d4 8552  .(1.D......_...R
00000040: 4b24 40a9 6f89 6692 74b7 5455 b817 ea86  K$@.o.f.t.TU....
00000050: aa7f febf 2f93 ccb9 9245 99e6 d37f 3dc3  ..../....E....=.
00000060: 43f4 cc91 539e 8b74 3afa d7b3 5f3e 7d3f  C...S..t:..._>}?
00000070: 089f fdbf 6fcf fe39 9115 13ac 620e 804f  ....o..9....b..O
00000080: cb7f 3d1b 57d5 ec9b f3f3 2c9d cebf 0cc5  ..=.W.....,.....
00000090: fcb3 1c4a 313f 5f42 9df3 7c32 c9a7 cf6a  ...J1?_B..|2...j
```

```
[dalley@thinkpad Downloads]$ xxd af12533499469117e3824bc938bfc3208539deb44bbf56ec2612fc383b28a1f4 | head
00000000: 1f8b 0800 0000 0000 0003 ed5a e96e db48  ...........Z.n.H
00000010: 12fe afa7 68f0 cfd8 48c4 a349 369b 81ac  ....h...H..I6...
00000020: 81c7 c964 6691 5dcc c231 d6f3 cbe8 8b52  ...df.]..1.....R
00000030: af79 6879 c8d6 3ccd becb bed8 5693 9445  .yhy..<.....V..E
00000040: 2763 8752 2686 6104 302c b254 555d 577f  'c.R&.a.0,.TU]W.
00000050: 55dd f6ec c7db 2c45 6b55 56ba c84f 2ccf  U.....,EkUV..O,.
00000060: 762d a472 5148 9d2f 4eac 8b8f 3f4f a9f5  v-.rQH./N...?O..
00000070: e37c 32cb 54cd 24ab 1902 f6bc 3ab1 9675  .|2.T.$.....:..u
00000080: bd7a e338 a9ce 9b5b 5b36 d7ca 56b2 71b6  .z.8...[[6..V.q.
00000090: 5c8e 28b2 acc8 ad8e fb4d b9ca be28 013c  \.(......M...(.<
```

**Comment by ppisar** [comment] 2023-03-27 13:05
createrepo_c uses file (magic) library underneath. Hence it's correct that both crearerepo_c and file tool agree. I suspect that's an regression in an update of file-libs RPM package. Could you try an older file-libs version? Or share with us the misdetected archive?

**Comment by ppisar** [comment] 2023-03-27 13:07
createrepo_c uses file (magic) library underneath. Hence it's correct that both crearerepo_c and file tool agree. I suspect that's an regression in an update of file-libs RPM package. Could you try an older file-libs version? Or share with us the misdetected archive?

**Comment by ppisar** [comment] 2023-03-27 13:14
Sorry, for the double post.
I reversed your af12533499469117e3824bc938bfc3208539deb44bbf56ec2612fc383b28a1f4 sample into a binary file and I cannot reproduce the misdetection. I tried file-libs-5.41-4.fc36.x86_64 and file-libs-5.44-3.fc39.x86_64. What's your file-libs version?

**Comment by dralley** [comment] 2023-03-27 13:16
I'm on Fedora 36 but I believe this can also be reproduced on EL8

**Comment by dralley** [comment] 2023-03-27 13:18
I looped in @vmihalko on Slack as the maintainer of the file library

**Comment by ppisar** [comment] 2023-03-27 13:29
I found that file at <https://download.copr.fedorainfracloud.org/results/audron/dexed/fedora-38-aarch64/repodata/af12533499469117e3824bc938bfc3208539deb44bbf56ec2612fc383b28a1f4-primary.xml.gz>. Supplying the whole file reveals the failure:

~~~~
$ gzip -tv af12533499469117e3824bc938bfc3208539deb44bbf56ec2612fc383b28a1f4-primary.xml.gz 
af12533499469117e3824bc938bfc3208539deb44bbf56ec2612fc383b28a1f4-primary.xml.gz:         OK
$ file af12533499469117e3824bc938bfc3208539deb44bbf56ec2612fc383b28a1f4-primary.xml.gz 
af12533499469117e3824bc938bfc3208539deb44bbf56ec2612fc383b28a1f4-primary.xml.gz: DOS/MBR boot sector; partition 1 : ID=0x4b, active 0xd0, start-CHS (0x63,239,44), end-CHS (0x33d,134,0), startsector 316955931, 1708404748 sectors; partition 3 : ID=0x53, active 0xaa, start-CHS (0x33a,156,2), end-CHS (0x22c,176,51), startsector 1315648692, 2595702924 sectors; partition 4 : ID=0x3a, active 0xca, start-CHS (0x1d5,97,37), end-CHS (0x28b,241,55), startsector 2173204403, 2875341233 sectors
$ rpm -q file-libs
file-libs-5.44-3.fc39.x86_64
~~~~

That's a clear failure of file tool (libmagic database).

Please understand that the detection is always only approximate. For createrepo_c, please always keep a suffix in the file name. It's a way how YUM repository metadata deliver the compression algorithm. And it's the only way which avoid the detection.

I recommend closing this createrepo_c issues as we cannot fix it on createrepo_c side.

**Closed** 2023-03-27 13:36 UTC
