### ISSUE TITLE
bad epoch in version string

### ISSUE THREAD

**Issue by furlongm** [rpm-software-management/createrepo_c#166] opened 2019-06-11 16:24 UTC
Getting bad epoch in version string error when syncing RHEL6 mirrors. The following is an example:

```
C_CREATEREPOLIB: Warning: Bad epoch in version string "%1:2.0.3" for dependency "openoffice.org-langpack-zu" in package "libreoffice-langpack-zu-1:4.2.8.2-11.el6_7.1.x86_64"
C_CREATEREPOLIB: Warning: Skipping this dependency
```

**Comment by kontura** [comment] 2019-06-12 10:42
I think there was a problem with the specific package libreoffice-langpack-zu-4.2.8.2-11.el6.x86_64.rpm

I tried:
`$ rpm -q --obsoletes libreoffice-langpack-zu-4.2.8.2-11.el6.x86_64.rpm`
and the output contained:
`openoffice.org-langpack-zu < %1:2.0.3`
The "%" character is causing the problem and is not supposed to be there.

Therefore I would say this is not a bug in createrepo_c.
Also it is fixed in newer versions of the package.

**Closed** 2019-06-15 20:19 UTC
